version: '3.8'

services:
  skyvault:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./encrypted_files:/app/encrypted_files
    restart: unless-stopped
